name: Bump Envoy Image

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight.

  workflow_dispatch: # Allow manual runs.

permissions:
  contents: write # Required to push changes to the repository.
  pull-requests: write # Required to create a pull request.

env:
  GOPROXY: https://proxy.golang.org/
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump-envoy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: "main"
            envoy-release-track: "v1.33"
    #       - branch: "release-1.30"
    #         envoy-release-track: "v1.31"
    #       - branch: "release-1.29"
    #         envoy-release-track: "v1.30"
    #       - branch: "release-1.28"
    #         envoy-release-track: "v1.29"

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "stable"
          cache: false

      - name: Run bump-envoy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go run hack/actions/bump-envoy.go \
            --release-track ${{ matrix.envoy-release-track }} \
            --output-version-file new-envoy-version.txt \
            --commit-message-file commit-message.txt
          echo "target_envoy_version=$(cat new-envoy-version.txt)" >> $GITHUB_ENV
          echo "pr_branch_name=github-actions/envoy/${{ matrix.branch }}/envoy-$(cat new-envoy-version.txt)-bump-for" >> $GITHUB_ENV

      - name: Check if the PR branch already exists
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.pr_branch_name }}; then
            echo "PR branch ${{ env.pr_branch_name }} already exists. Exiting."
            exit 1
          fi

      - name: Check for changes
        id: check_for_changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if git diff --exit-code; then
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Create new branch and push changes
        if: env.changes_detected == 'true'
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.pr_branch_name }}; then
            echo "Branch ${{ env.pr_branch_name }} already exists. Exiting."
            exit 1
          fi

          git checkout -b ${{ env.pr_branch_name }}
          git add -u
          git commit -sm "Bump Envoy to ${{ env.target_envoy_version }}"
          git push origin ${{ env.pr_branch_name }}

      - name: Create Pull Request
        if: env.changes_detected == 'true'
        run: |
          gh pr create --body "$(cat commit-message.txt)" \
                       --head "${{ env.pr_branch_name }}" \
                       --base "${{ matrix.branch }}" \
                       --label "area/dependency" \
                       --label "release-note/none-required" \
                       --title "Bump Envoy to ${{ env.target_envoy_version }} in ${{ matrix.branch }}"
